### ISSUE TITLE
Insecure HTTP repository

### ISSUE THREAD

**Issue by WhittlesJr** [peterschwarz/clj-serial#9]
On Windows:

lein repl
Retrieving clj-serial/clj-serial/2.0.0/clj-serial-2.0.0.pom from clojars
Tried to use insecure HTTP repository without TLS.
This is almost certainly a mistake; however in rare cases where it's
intentional please see `lein help faq` for details.

I don't have this problem on Linux for whatever reason. It's caused by:

  :repositories [["javacomm" "http://www.sparetimelabs.com/maven2"]]

Pull request coming with a seemingly easy fix, although I'm not sure if it'll cause problems.

**Comment by WhittlesJr** [comment]
Well that didn't work. Thoughts?

**Comment by peterschwarz** [comment]
You could test it against this version of the dependency in the main Maven repository (and remove that `:repositories` entry):
```
[com.github.purejavacomm/purejavacomm "1.0.2.RELEASE"]
```

**Comment by kaosbeat** [comment]
Adding the repositories entry does not help on OSX...
Can I somehow manually install?

**Comment by howarth** [comment]
Hello, I think I'm having the same issue.

`
Retrieving org/clojure/clojure/1.8.0/clojure-1.8.0.pom from central
Retrieving clj-serial/clj-serial/2.0.4-SNAPSHOT/clj-serial-2.0.4-20160417.195526-4.pom from clojars
Tried to use insecure HTTP repository without TLS.
This is almost certainly a mistake; however in rare cases where it's
intentional please see `lein help faq` for details.
`

This happens on Ubuntu 16.0.4.3 LTS.
This doesn't happen when I'm on my Mac with high sierra installed.

Here's my project file:

`
(defproject present "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.8.0"]
                 [clj-serial "2.0.4-SNAPSHOT"]
  ]
  :main ^:skip-aot present.core
  :target-path "target/%s"
  :profiles {:uberjar {:aot :all}})
~                                                 
`

**Comment by howarth** [comment]
However, if I just clone this repo and run `lein repl` inside `clj-serial` then I have no issues.

**Comment by peterschwarz** [comment]
I haven't yet pushed the new build up, that changes the dependencies (which
is what you're using if you cloning the repo).  I'll hopefully get a chance
to do that soon.

**Comment by WhittlesJr** [comment]
The current state of develop is working for me as well.

**Comment by WhittlesJr** [comment]
ping

**Comment by WhittlesJr** [comment]
It looks like this is fixed in 2.0.5
